### ISSUE TITLE
generate_unitsegments doesn't use any RF estimation.

### ISSUE THREAD

**Issue by zym1010** [metalbubble/unitvisseg#1]
Based on description of Figs 4 and 5 in the paper, it seems that, in Figure 5, the shapes of RFs are derived from those in Figure 4, using an expensive estimation procedure. But in practice, seems that  this estimation procedure is not used at all.

**Comment by metalbubble** [comment]
Yes, bilinear sampling of the feature map to the original input image size is good enough to generate a reasonably well segmentation, though the RF generated from the expensive estimation procedure generates tighter segmentation result.
